[build-system]
requires = ["setuptools>=42", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
authors = [{ name = "Alexander S. Shved", email = "shvedalx@illinois.edu" }]
requires-python = ">=3.10,<3.11"
name = "molli"
description = "Molecular toolbox library"
# dynamic = ["version"]
dependencies = [
    "numpy>=1.22.3",
    "scipy>=1.9.1",
    "attrs~=22.1.0",
    "packaging~=22.0",
    "bidict~=0.21.2",
    "requests~=2.28",
    "PyYAML~=5.3",
    "msgpack~=1.0.3",
    "scipy>=1.4.1",
    "colorama>=0.4.4",
    "networkx>=2.8.7",
    "tqdm~=4.64.0",
    "h5py~=3.7.0",
    "pyvista~=0.37",
]
version = "1.0.0a7"

[tool.setuptools.packages.find]
include = ["molli", "molli_test"]

[project.scripts]
molli = "molli.__main__:main"

# [tool.setuptools.dynamic]
# version = { attr = "molli.__version__" }
