# ================================================================================
# This file is part of
#      -----------  
#      MOLLI 1.0.0  
#      -----------  
# (C) 2022 Alexander S. Shved and the Denmark laboratory
# University of Illinois at Urbana-Champaign, Department of Chemistry
# ================================================================================

{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True)  %}
# tool.setuptools.dynamic
{% set version = pyproject.get('project').get('version') %}


package:
  name: molli
  version: {{ version }}
  
about:
  summary: "Molecular Library Toolkit"
  description: |
    This package was originally developed to supersede ccheminfolib. 
    Now it is a tool that allows storage and fast manipulations of full molecule and conformer ensembles.
    This project takes advantage of numpy mathematics in its core, as well as binary information storage.

source:
  path: ..

requirements:
  host:
    - python {{ python }}
    - setuptools>=60
    - {{ compiler("cxx") }}
    - pybind11~=2.10

  run:
    - python {{ python }}
    - numpy~=1.24.0
    - scipy~=1.9.1
    - h5py>=3.8
    - msgpack-python>=1.0.4
    - attrs>=22.1.0
    - bidict>=0.21.2
    - networkx~=3.0
    - colorama>=0.4.5
    - tqdm>=4.64.0
    - pyyaml>=5.4.1
    - requests>=2.28
    - packaging>=23.1

build:
  number: 0
  include_recipe: True
  script: "python -m pip install --no-deps -vvv ." 

test:
  imports:
    - molli
    - molli_test
    - molli_xt