# ================================================================================
# This file is part of `molli 1.0` 
# (https://github.com/SEDenmarkLab/molli)
# ================================================================================

{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True)  %}
# tool.setuptools.dynamic
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.999') %}


package:
  name: molli
  version: {{ version }}
  
about:
  home: https://github.com/SEDenmarkLab/molli
  license: MIT
  license_file: LICENSE
  summary: "Molecular Library Toolkit"
  description: |
    Molli is a toolbox that allows storage and fast manipulations of full molecule and conformer ensembles.
    This project takes advantage of numpy mathematics in its core, as well as binary information storage.
    Molli offers a convenient interface to familiar chemical concepts such as Atom, Molecule, ConformerEnsemble, etc.
    See README.md for more details.
  dev_url: https://github.com/SEDenmarkLab/molli
  doc_url: https://molli.readthedocs.io/en/latest/

source:
  path: ..

requirements:
  host:
    - python {{ python }}
    - setuptools>=60
    - {{ compiler("cxx") }}
    - pybind11~=2.10

  run:
    - python {{ python }}
    - numpy~=1.24.0
    - scipy~=1.9.1
    - h5py>=3.8
    - msgpack-python>=1.0.4
    - msgpack-numpy>=0.4.8
    - attrs>=22.1.0
    - bidict>=0.21.2
    - networkx~=3.0
    - colorama>=0.4.5
    - tqdm>=4.64.0
    - pyyaml>=5.4.1
    - requests>=2.28
    - packaging>=23.1
    - deprecated>=1.2.14
    - fasteners>=0.16
    - joblib>=1.3.2

build:
  number: 0
  include_recipe: True
  script: "python -m pip install --no-deps -vvv ."
  entry_points:
    - molli = molli.__main__:main
    - _molli_run = molli.pipeline.runner:run_local
    - _molli_run_sched = molli.pipeline.runner:run_sched

test:
  imports:
    - molli
    - molli_test
    - molli_xt
