# ================================================================================
# This file is part of
#      -----------  
#      MOLLI 1.0.0  
#      -----------  
# (C) 2022 Alexander S. Shved and the Denmark laboratory
# University of Illinois at Urbana-Champaign, Department of Chemistry
# ================================================================================

package:
  name: molli
  version: 1.0.0a6
  
about:
  summary: "Molecular Library Toolkit"
  description: |
    This package was originally developed to supersede ccheminfolib. 
    Now it is a tool that allows storage and fast manipulations of full molecule and conformer ensembles.
    This project takes advantage of numpy mathematics in its core, as well as binary information storage.

source:
  path: ..

requirements:
  build:
    - python>=3.10,<3.11
    - setuptools>=60
    - {{ compiler("cxx") }}
    - pybind11~=2.10

  run:
    - python>=3.10,<3.11
    - numpy>=1.22.3
    - scipy>=1.9.1
    - attrs~=22.1.0
    - bidict~=0.21.2
    - msgpack-python>=1.0.4
    - networkx~=2.8.7
    - colorama~=0.4.5
    - tqdm~=4.64.0
    - pyyaml~=5.4.1
    - dask~=2022.9.1
    - requests~=2.28
    - h5py~=3.7.0
    - openbabel~=3.1.1

build:
  number: 0
  include_recipe: True
  script: "python -m pip install --no-deps -vv ." 

test:
  imports:
    - molli
    - molli_test
    - molli_xt


