name: publish_conda

on:
  release:
    types: [published]
  
  # Temporary: for debug purposes only
  pull_request:



jobs:
  conda_build:
    name: Build and upload conda package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]        
    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        # with:
        #   create-args: >-
        #     python=3.11
        #     conda
        #   environment-name: molli
        #   #environment-file: environment.yml
        #   #cache-environment: true
        #   #generate-run-shell: true
        #   # condarc: |
        #   #   channel_priority: flexible
        #   #   channels:
        #   #     - conda-forge

      - name: Build conda package
        env:
          ACTIONS_STEP_DEBUG: true
          LABEL: test
        run: |
          conda install conda-build;
          mkdir conda_dist;
          conda build --output-folder conda_dist \
                      --label ${{ env.LABEL }} \
                      conda-recipe
      
       - name: Upload conda package
        env:
          ACTIONS_STEP_DEBUG: true
          LABEL: test
        run: |
          # TODO: Parse/set VERSION number accordingly
          
          conda install -y anaconda-client
          anaconda --token ${{ secrets.CONDA_TOKEN }} upload \
                          --user esalx \
                          --label ${{ env.LABEL }} \
                          conda_dist/*/molli-*.tar.bz2
