name: publish_conda

on:
  release:
    types:
      - published
      - edited
      - created
  

jobs:
  conda_build:
    name: Conda ${{ matrix.os }} build and upload 
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: >-
            bash
            powershell

          create-args: >-
            python=3.11
            conda


          environment-name: molli

        #   #environment-file: environment.yml
        #   #cache-environment: true
        #   #generate-run-shell: true
        #   # condarc: |
        #   #   channel_priority: flexible
        #   #   channels:
        #   #     - conda-forge
      
      - name: Install conda build and upload dependencies
        run: |
          conda install -y conda-build anaconda-client

      - name: Build conda package
        env:
          ACTIONS_STEP_DEBUG: true
          LABEL: test
        run: |
          mkdir conda-dist;
          conda build --output-folder conda-dist --label ${{ env.LABEL }} conda-recipe;
      
      - name: Upload conda package
        env:
          ACTIONS_STEP_DEBUG: true
          LABEL: test
        run: |
          anaconda --token ${{ secrets.CONDA_TOKEN }} upload --user esalx --label ${{ env.LABEL }} --force conda-dist/*/molli-*.tar.bz2; 
