name: Upload Anaconda Package

on:
  push:
    branches:
      - "**" # Runs on all branches
  release:
    types:
      - published
  

jobs:
  conda_build:
    name: Conda ${{ matrix.os }} build and upload 
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false #Allows other OS builds to run if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set up MSVC (Windows only)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Delete Incorrect Link from Path
        if: matrix.os == 'windows-latest'
        run: rm /usr/bin/link.exe

      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: >-
            bash
            powershell

          create-args: >-
            python=3.11
            conda
            conda-build
            anaconda-client

          environment-name: molli

      - name: Build conda package
        env:
          ACTIONS_STEP_DEBUG: true
        run: |
          mkdir conda-dist;
          conda build --output-folder conda-dist conda-recipe;
      
      - name: Upload conda package
        env:
          ACTIONS_STEP_DEBUG: true
          ANACONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
        run: |
          # Find file regardless of OS path
          FILE_PATH=$(find conda-dist -name "molli-*.tar.bz2" | head -n 1) 

          anaconda --token $ANACONDA_TOKEN upload --user esalx --label dev --force "$FILE_PATH"; 
