name: molli_package_test
on:
  pull_request:
       

permissions:
  contents: read

jobs:
  molli_test:
    name: Testing on py${{ matrix.py_version }}, ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}

    # defaults:
    #   run:
    #     shell: bash -l {0}

    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest 
          - macos-latest
        
        py_version:
          - "3.10"
          - "3.11"
          - "3.12"
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py_version }}
        
      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip;
          mkdir temp;
        
      - name: Install molli package
        run: |
          pip install . -vv
      
      - name: Run molli test suite
        working-directory: temp
        run: |
          molli test -vvv
    
        

    