# This version of code testing is done on pull requests
# To ensure that code tests run on all supported OS
# with the earliest and the latest supported version of Python

name: Minimal code testing
on:
  pull_request:
       

permissions:
  contents: read

jobs:
  molli_test:
    name: Testing on ${{ matrix.os }}, python=${{ matrix.py_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest 
          - macos-latest
        
        py_version:
          - "3.10"
          - "3.13"
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py_version }}
        
      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip;
          mkdir temp;
        
      - name: Install molli package
        run: |
          pip install . -vv
      
      - name: Run molli test suite
        working-directory: temp
        run: |
          molli test -vvv
    
        

    